# Generated by Django 4.1.2 on 2022-10-24 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_shippingaddress_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="order",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="base.order"
            ),
        ),
    ]
